### ISSUE TITLE
VMCS: Defect: The simulation currently does not clear the values on the completion of a Maintenance session.

### ISSUE THREAD

**Issue by MrNayLA** [MrNayLA/SE25PT7ConfigMgnt_CA2#1]
Reset the values to null for “Show Total Cash Held” and “Press to Collect Cash” when the
Maintainer successfully pushes “Press Here When Finished”. The simulation currently does
not clear the values on the completion of a Maintenance session. Upon a subsequent re-login
to the Maintenance Panel in the same session, the cash previously held and already collected,
persists in display. This sometimes causes confusion to Maintainer.

**Comment by MrNayLA** [comment]
Fixed the defect/bug in the following commit.
Date:			57 seconds ago (15/09/2018 6:17:48 PM)
Commit hash:	a83a9f033936f29b8202e1dcc00421f848715db0

**Comment by KaungMyatBo** [comment]
Cool, It is good to go.

**Comment by MrNayLA** [comment]
Closed the issue :-1: 
VMCS: Defect: The simulation currently does not clear the values on the completion of a Maintenance session. #1
