### ISSUE TITLE
VMCS : Enhancement : aid the Maintainer

### ISSUE THREAD

**Issue by gaozhiyu** [MrNayLA/SE25PT7ConfigMgnt_CA2#2]
This will enable the Maintainer to readily tally the total cash collected and the total number of coins by denomination displayed in “Show Total Cash Held” and “Press to Collect Cash” when pressed, thus leaving no room for dispute over system errors.

**Comment by NBS-Bala** [comment]
Check the changes, tested and verified the results.  We can closed this issue as being verified, committed and ready to be released
